FROM node:22-bookworm-slim


# コンテナ内の作業ディレクトリを/appに設定
WORKDIR /app

# 依存関係をコピーしてインストール
COPY package.json package-lock.json ./
RUN npm install 

COPY . .


# フロントエンドのポートを設定
EXPOSE 3000

# 開発サーバー: 0.0.0.0ホストで公開することで、コンテナ外からもアクセスできるようにする。
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]