FROM node:24

WORKDIR /app

# パッケージファイルをコピー
COPY package.json package-lock.json ./

# 依存関係をインストール
RUN npm ci

# ソースコードをコピー
COPY . .

# 本番ビルド
RUN npm run build


# 本番サーバーを起動
CMD ["npm", "run", "serve"]